### ISSUE TITLE
[RFE] [Tracking] issue for minor enhancements and improvements

### ISSUE THREAD

**Issue by t-lo** [flatcar/flatcar-mastodon#5]
## New features
- [ ] mastodon-cron job to run recurring clean-up jobs like image cache clearing etc
- [ ] `update.conf` integration with custom [maintenance / reboot window](https://flatcar-linux.org/docs/latest/setup/releases/update-strategies/#auto-updates-with-a-maintenance-window)

## enhancements
- [ ] restart policy for `.service` files
